apply plugin: 'java'
apply plugin: 'application'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:5.6.3'
    implementation 'org.slf4j:slf4j-simple:2.0.16'
    implementation 'com.squareup.okhttp3:okhttp:3.12.3'
    implementation 'org.jsoup:jsoup:1.12.1'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainClassName = 'com.hippo.server.Main'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.hippo.server.Main'
        )
    }
}
