apply plugin: 'java'
apply plugin: 'application'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jsoup:jsoup:1.12.1'
    implementation 'com.squareup.okhttp3:okhttp:3.12.3'
}

application {
    mainClassName = 'com.hippo.desktop.Main'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
